### PR TITLE
fixes 429 "Too Many Requests" retries that don't follow standard

### LINKED ISSUE #24: 429 "Too Many Requests" HTTP code doesn't implement standard seconds value case
## Description of the issue

Previously reported in tcort/markdown-link-check#114 this issue is in fact a link-check issue.

This issue has multiple parts linked together that have to be fixed at once.

### Retry-After header format

The retry on 429 "Too Many Requests" HTTP code implemented in link-check expects a non standard retry format for the Retry-After optional header.
It looks for a duration of the form "1m30s" (for 1 minute 30 secondes) despite the standard being clear that the value format is seconds (or an http date format but I never saw that, so we may be safe to only have seconds) 
See <https://tools.ietf.org/html/rfc7231#section-7.1.3>

### Conversion error

But this would not be an issue if there was not also a conversion error.

For instance "Retry-After: 60" meaning wait for 60s before retry. 

Link-check uses the [Node.js `ms` library](https://www.npmjs.com/package/ms) to converts in milliseconds.
It splits the string in parts to have "1m30s" look like "1m 30s" which is suitable for `ms`.
But `ms` is not applying any change on the value when it's already an integer.
`ms(60)` for 60 seconds from the "Retry-After: 60" becomes 60 milliseconds instead of 60000 and of course fails as it's too soon for the retry.

## Fixing

We have to fix:

- accept the standard seconds format.
- convert "Retry-After" integer value in milliseconds.

## Compatibility

[Github recently fixed their issue](https://github.com/urllib3/urllib3/issues/1822) that was returning "XmXXs" format retry headers to conform to the standard format in seconds and @sethmlarson says in the similar [urllib3 issue](https://github.com/urllib3/urllib3/issues/1822):
>We're going to close this issue as "not a defect in urllib3". GitHub needs to fix their headers.

But I think we should keep compatibility with the already implemented non standard way as it may impact some users.

We need to support "XmXXs" format and add the correct standard seconds support.

## Testing

429 HTTP code testing must be added to the library and ensure that the retry delay value is well interpreted.
Test have to check that returning a "Retry-After:60" makes the second attempt wait for at least 60 seconds.

### PR DESCRIPTION
**Pull request by NicolasMassart**
Some HTTP servers return a non standard 'retry-after' header with incorrect values according to <https://tools.ietf.org/html/rfc7231#section-7.1.3> and <https://tools.ietf.org/html/rfc6585#section-4>

This PR provides:

- standard compliant retry delay duration handling
- error message provided to inform user in case of non standard server response (non breaking as it still returns the success code if the link is finally reached with a code 200)
- provide tests for the 429 "Too Many Requests" retries case
- merged with changes from #22 and fixed issues that it brought to my changes
  - Added a default value to 2 for retries in the http and not only on the CLI
  - removed a redundant test case
  - updated custom retry test to match others
- add a default retry delay in case of no retry-after header is present in the server response (see [rfc6585](https://tools.ietf.org/html/rfc6585#section-4)). The default is 60s but can be overridden by config.
- move config defaults to the relevant place (http protocol only)

The suggested error message in this PR is to deprecate non standard response starting from link-check 4.5.2 (next release) and totally remove it for 4.7.0.

fixes #24

### CODE REVIEW

**Comment by NicolasMassart** [comment]
@andreizet I would be happy to have your opinion on this PR please.

**Comment by NicolasMassart** [comment]
@cmgrote Given the 429 non standard feature was only introduced by your PR on April 6th this year and it seems related to Github given the original issue is odpi/egeria#2763, maybe the error message and keeping the compatibility part is not useful. It would simplify a lot to be honest. Did you notice failures on your project since Github updated the header to seconds?

**Comment by andreizet** [comment]
> @andreizet @cmgrote I would be happy to have your opinion on this PR please.

Awesome! This should save us a lot of headache. Since the support for non standard `retry-after` will be dropped in 4.7.0, there should be a viable default for this case.

**Review by cmgrote — APPROVED** [review]
Sounds good -- I believe you are correct that GitHub has corrected their non-standard time formatting, as I now see various 429 errors again from their side in the link checker.

**Comment by NicolasMassart** [comment]
@andreizet
>Since the support for non standard `retry-after` will be dropped in 4.7.0, there should be a viable default for this case.

Do you mean for instance if we have a 429 but no header (it's optional in the RFC) or an invalid one we should have a default value, say 60s?

**Comment by andreizet** [comment]
> @andreizet
> 
> > Since the support for non standard `retry-after` will be dropped in 4.7.0, there should be a viable default for this case.
> 
> Do you mean for instance if we have a 429 but no header ([it's optional in the RFC](https://tools.ietf.org/html/rfc6585#section-4)) or an invalid one we should have a default value, say 60s?

Yep, something like that, but also, there may be cases when 60 seconds are not enough.

**Comment by NicolasMassart** [comment]
@andreizet, I agree for the default.
For the 60s not being enough, if servers have such requirements, they should probably send a retry-after header.
But implementing an [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) retry may be the way.
See [urllib3](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html) or this interesting [Google implementation of truncated exponential backoff](https://cloud.google.com/storage/docs/exponential-backoff).
However, I would prefer to handle that in another PR.

**Comment by NicolasMassart** [comment]
@andreizet I added a 60s default fallback delay that you can override with config, see 015cd8a

**Pull request merged**
