### PR TITLE
Replace isemail, convert to ES6 module

### PR DESCRIPTION
**Pull request by rkitover**
Replace isemail with node-email-verifier, which also checks that email
domains have an MX record.

Add support for the timeout option for domain MX verification.

This also fixes the deprecation warning for the punycode module, which
is a dependency of isemail.

Convert module to ES6 with `"type": "module"` in package.json. This will
mean that users will need to import into an ES6 module or use one of the
workarounds for cjs such as `await import`.

### CODE REVIEW

**Comment by rkitover** [comment]
sorry I'm still working on this, I opened this by accident

**Comment by rkitover** [comment]
could you run the CI please?

**Comment by nschonni** [comment]
You can turn on Actions on your own fork https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository then you can test as much as you want

**Comment by rkitover** [comment]
I don't see actions at all in my fork.

**Comment by rkitover** [comment]
@tcort this is ready for review.

**Comment by rkitover** [comment]
@tcort I simplified this using a PR I did for node-email-verifier to add the timeout option there.

**Comment by rkitover** [comment]
@tcort Can you look at this please, the main issue is that this fixes the deprecation warning for the pynycode module.

If you don't want it to be an ES6 module I can convert it back to cjs.

**Comment by MikeMcC399** [comment]
- This is related to https://github.com/tcort/link-check/issues/92

Maybe a minimal PR which **only** replaces `isemail`, without additional enhancements, would be easier to review and merge? It would be good to get some feedback from @tcort on this.

**Comment by rkitover** [comment]
I can convert back to cjs which will make this only a couple of lines, would you like me to?

**Comment by MikeMcC399** [comment]
@rkitover 

> I can convert back to cjs which will make this only a couple of lines, would you like me to?

If you ask me, then "yes". However bear in mind that I am not a maintainer of this repo, or the owner of it. It's just my personal opinion.

**Comment by rkitover** [comment]
Moved here:

https://github.com/tcort/link-check/pull/94
.

**Pull request closed without merging**
