### PR TITLE
Convert the whole library to typescript

### PR DESCRIPTION
**Pull request by boillodmanuel**
Hi,

As I was using this lib and wanted to contribute to, I have convert the whole project to typescript (it's easier to me).

With this version I introduced an API change (I documented it in `CHANGELOG`). There can be a solution for keeping the same API, but I don't know if module export is still a best practice. By the way, I don't know how to do it in typescript.

You'll find another interesting dev stuff in the `CONTRIBUTING` file.

Best regards,

### CODE REVIEW

**Comment by boillodmanuel** [comment]
The git diff is not very easy to use as I moved files in `src` folder and renamed them with `.ts` extension. But the code is pretty much the same. I only split http.check method into several methods.

**Comment by boillodmanuel** [comment]
If you want to see an improvement I did : https://github.com/boillodmanuel/link-check/pull/1 - Add `debug`, `debugToStdErr` and `retryOnError` options

**Comment by nschonni** [comment]
I'd probably swap TSLint for ESLint, since TSLint is deprecated https://www.darraghoriordan.com/2020/03/06/upgrade-tslint-deprecated-to-eslint/

**Comment by boillodmanuel** [comment]
Still work in progress, but I converted the `markdown-link-check` repo too.
I also add an API for processing multiples inputs.
I did not convert the binary.
You can take a look here : https://github.com/boillodmanuel/markdown-link-check/tree/master
(note that I also updated my `link-check` `master` branch here : https://github.com/boillodmanuel/link-check/tree/master

**Comment by boillodmanuel** [comment]
@nschonni I migrated to ESLint.
@tcort I kept this PR open but I don't try to keep compability as I added much features like statistics, etc
I did the same for markdown-link-check with lot of improvements too but didn't open a PR. Let me know if you're interested in

**Comment by NicolasMassart** [comment]
Hi @boillodmanuel that nice that you want to contribute. We need that.
However, one nice thing is to discuss such important changes ([we now have the discussions activated on this repos](https://github.com/tcort/link-check/discussions) for future things like this).

I honestly don't know if we want to move to TS (I'm not a lot in TS myself even if, as a Java dev, I understand the interest of typing, I don't have a lot of experience with it) but it also seems to me that both are compatible and we have to be convinced that we need to switch.
As you will guess, the argument of yourself being more confortable in TS is not enough. I'm more confortable with Java but won't suggest a Java version of this tool.

So if you could give us some reasons to switch and the issues it will generate, that would be nice.
Also consider that retro-compatibility is required. We can't break all our users setup for that.

Thanks for your understanding.

**Comment by boillodmanuel** [comment]
Hi Nicolas,

Thanks for your feedback.

I don't want to argue a lot on why TS is better. The main thing is that a
part of javascript ecosystem is moving to typescript, and that people are
looking for typescript compatible library (at least there should be a type
declaration file for the API).

Secondly, I bring a log of improvement (for me) in the library itself on
my fork (including markdown-link-check). I'm happy with the result.
I will not spend much time figuring out how to preserve
retro-compatibility, but if you are interested in my PR, you can use it.
Otherwise you can close it.

Best regards,

Manuel


Le jeu. 10 déc. 2020 à 11:30, Nicolas MASSART <notifications@github.com> a
écrit :

**Comment by NicolasMassart** [comment]
@boillodmanuel thanks for your answer.
My personal priority is our community and compatibility and I notice it's not yours for the moment. But that's not a reason not to discuss ;)
Still there're nice things in your PR, we may be inspired by some.
I will wait for some other opinion including @tcort of course.

Otherwise, I think an open source project is made to be forked, what you did. That's part of the life cycle.
I personally don't see any reason why we could not have both JS and TS at the same time and feed each other with the improvements from the other. Community will decide what fork is the best for them in the end.

**Comment by tcort** [comment]
I'm happy with keeping it a JavaScript library for now.

**Pull request closed without merging**
